config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :friends

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create" 
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update" 

  delete "logout", to: "session#destroy"

  get "workspace/list", to: "workspaces#new"

  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/friend.rb
class Friend < ApplicationRecord
    # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    # has_many :friend, dependent :destroy
    attr_accessor :remember_token
    before_save :casedown_email

    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\$]+@[^@\$]+\z/, message: "must be a valid email address" }, uniqueness: true
    validates :password, presence: true, length: {minimum: 5, maximum: 10}

    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.new_token
        SecureRandom.urlsafe_base64
    end


    def casedown_email 
        self.email = email.downcase
    end

    def remember 
        self.remember_token = self.new_token
        update_attribute(:remember_digest, self.digest(remember_token))
    end

    def authenticated?(remember_token) 
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_id!
        redirect_to sign_in_path, alert: "User should be logged in" if Current.user.nil?
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :facebook)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            #Send the mail to the exitsting user
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path, notice: "If the email you supplied exit, then you will get a email to reset your password"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "reset_password")
    rescue ActiveSupport::MessageVerifier::InvalidSignature 
        redirect_to sign_in_path, alert: "Soory, the token has expired, Please try again"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "reset_password")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Pasword has been updated!"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_id!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated!"
        else
            render :edit
        end
    end

    private
    
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  # validates :password, { length: {minimum:5, maximum:10} }

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      redirect_to root_path, notice: "Successfully Created Account."
    else 
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email].downcase)
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged In Successfully"
        else
            flash[:alert] = "Invalid Credentials"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out Successfully.."
    end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController

    def new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helpers.rb
module SessionHelper 
    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Facebook</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.facebook %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class: "btn btn-primary" %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Facebooke:</strong>
  <%= @friend.facebook %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-primary" %>
<%= link_to 'Back', friends_path, class: "btn btn-secondary" %>

app/views/home/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success mt-5" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger mt-5" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'CRUD APP', root_path, class: "navbar-brand" %>
    <%# <a class="navbar-brand" href="#">CRUD APP</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Show Friends', friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item px-5">
            <span class="nav-link"><%= Current.user.email %></span>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete,  class: "btn btn-danger" %>
          </li>
        <% else %>
          <li class="nav-item px-5">
            <%= link_to "Sign In", sign_in_path, class: "btn btn-success" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/home/index.html.erb
<% if Current.user %>
    <div class="mt-5 justify-content-center">
        <h1>Hello, Welcome To CRUD Application <span class="text-success"><%= Current.user.name %></span></h1>
    </div>
<% else %>
    <div class="mt-5 justify-content-center">
        <h1>Hello, Welcome To CRUD Application</h1>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class='container'>
      <%= render 'home/flash' %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1 class="mt-5">Reset Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
    <div class="mb-3">
        <label class="form-label">Password Confirmation</label>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1 class="mt-5">Reset Password</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/session/new.html.erb
<h1 class="mt-5">Sign In</h1>

<%= form_with url: sign_in_path do |form| %>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <%= form.text_field :email, class: "form-control", placeholder: "Type In Email" %>
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <%= form.password_field :password, class: "form-control", placeholder: "Type In Password" %>
    </div>
    <%= link_to "Forgot Password?", password_reset_path %>
    <div class="mb-3">
        <%= form.submit "Sign In", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/workspaces/new.html.erb
<h1>WorkSpace Brello</h1>